/*
initial db migration for projects and subtasks

Decisions:
- projects must have a name, whereas description is optional
- subtask requires project, again description is optional
- new subtasks are defaulted to incomplete
- ids and uuids are generated by postgresql
- each subtask belongs to an existing project through project_id
- dates are stpred with timestamps and timezones
- deleting projects deletes all related subtasks (ON DELETE CASCADE)
- project_id is indexed to make finding project's subtasks easier
*/

CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE subtasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_subtasks_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_subtasks_project_id
    ON subtasks(project_id);